zookeeper:
  image: confluentinc/cp-zookeeper:3.0.1
  ports:
    - "32181:32181"
  environment:
    ZOOKEEPER_CLIENT_PORT: 32181
    ZOOKEEPER_TICK_TIME: 2000

kafka:
  image: confluentinc/cp-kafka:3.0.1
  links:
    - zookeeper
  ports:
    - "29092:29092"
  environment:
    KAFKA_BROKER_ID: 1
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.99.100:29092

schema-registry:
  image: confluentinc/cp-schema-registry:3.0.1
  links:
    - zookeeper
    - kafka
  ports:
    - "8081:8081"
  environment:
    SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:32181
    SCHEMA_REGISTRY_HOST_NAME: localhost