zookeeper:
  image: confluent/zookeeper
  ports:
    - "2181:2181"

kafka:
  image: confluent/kafka
  links:
    - zookeeper
  ports:
    - "9092:9092"

schema-registry:
  image: confluent/schema-registry
  links:
    - zookeeper
    - kafka
  ports:
    - "8081:8081"
